# Imports

In [2]:
import torch

# Basics

Let's get some basic ideas out of the way

Probably the easiest way to setup the device variable.

This basically points to what torch will use to perform its operations moving forward. This tutorial has pretty innocent operations, but in the future, it will start mattering.

(I use CPU throughout)

In [3]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [5]:
tensor = torch.tensor([[1,2,1], [9,2,1]], dtype=torch.float16, 
                      requires_grad=True, device=device)

A tensor, to my understanding, is simply a **higher order matrix**, typically much higher in dimensions for us CS folks. A vector being 1-D, and a matrix being 2-D might be trivial versions of a matrix.

Why its **DIFFERENT** than puny vectors and tensors is because it assumes **multilinear relationships**

Great Source: [What is a tensor?](https://www.youtube.com/watch?v=bpG3gqDM80w)

In [10]:
# Some basic what-is-thats

print(tensor)
print(tensor.dtype) # Simply checks the type of tensor
print(tensor.requires_grad) # This is to track the tensor. More later.
print(tensor.shape) # The... shape, like a matrix, (rows, cols)

tensor([[1., 2., 1.],
        [9., 2., 1.]], dtype=torch.float16, requires_grad=True)
torch.float16
True
torch.Size([2, 3])


```requires_grad``` basically says this:

- I see that you have a tensor (variable)
- I see that you want me to track this
- If I track this, I will keep knowledge of its changes
- I can find its gradient
- When you want that, it will be available

If you build a simple neural network, you need to keep track of certain values to change them (weights during backpropagation for example). This helps us keep track of the things we want to probably CHANGE somehow

Some basic **init** methods

In [23]:
print(torch.eye(5)) # Creates an identity matrix
print(torch.ones([3,3])) # fills a nxm matrix with ones
print(torch.zeros([3,4]))# fills a nxm matrix with zeros
print(torch.rand([2,2])) # random numbers between 0 and 1 of some size you pass
print(torch.arange(0, 5)) # a for-loop-esque tensor with end not included


tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0.4847, 0.7672],
        [0.1894, 0.5836]])
tensor([0, 1, 2, 3, 4])


We can convert any py array type, or numpy array type to a tensor. This is usually done before processing anything for more efficient code

In [24]:
my_list = [i for i in range(6)]
print(torch.tensor(my_list))

tensor([0, 1, 2, 3, 4, 5])


### Arithmetic!

In [28]:
# Addition
x = torch.arange(0,5)
y = torch.arange(5,10)
z = x + y
print(z)

## You can be fancy and do:
z = torch.add(x, y)
print(z)

## add supports an alpha param though. This basically does x + a*y
z = torch.add(x, y, alpha=10)
z

tensor([ 5,  7,  9, 11, 13])
tensor([ 5,  7,  9, 11, 13])


tensor([50, 61, 72, 83, 94])

In [30]:
# Subtraction
x = torch.arange(0,5)
y = torch.arange(5,10)
z = y - x
print(z)

## You can be fancy and do:
z = torch.subtract(y, x)
print(z)

## subtract supports an alpha param as well.
z = torch.subtract(x, y, alpha=10)
z

tensor([5, 5, 5, 5, 5])
tensor([5, 5, 5, 5, 5])


tensor([-50, -59, -68, -77, -86])

In [64]:
# Multiplication
x = torch.arange(0,5)
y = torch.arange(5,10)
z = y * x
print(f"{x}, \n{y}, \n\t\t= \n{z}\n----------")

## You can do a matmul
z = x @ y
print(z) 

# Dot product is different. It will be:
mat1 = torch.rand(3)
mat2 = torch.rand(3)

print(torch.dot(mat1, mat2))

tensor([0, 1, 2, 3, 4]), 
tensor([5, 6, 7, 8, 9]), 
		= 
tensor([ 0,  6, 14, 24, 36])
----------
tensor(80)
tensor(0.9732)


In [52]:
# Division
# Multiplication
x = torch.arange(1,6)
y = torch.arange(5,10)
z = y / x 

print(f"{x}, \n{y}, \n\t\t= \n{z}\n----------")

## You can do this as well
z = torch.div(y, x)
print(z) 

tensor([1, 2, 3, 4, 5]), 
tensor([5, 6, 7, 8, 9]), 
		= 
tensor([5.0000, 3.0000, 2.3333, 2.0000, 1.8000])
----------
tensor([5.0000, 3.0000, 2.3333, 2.0000, 1.8000])


You will notice is casts the type automatically in the first division. Tensors are also supposed to be the same type. (Unlike python lists, ew)

In [56]:
# Exponents!
z = torch.pow(x, 2)
print(z)

# Or
z = x.pow(2)
z


tensor([ 1,  4,  9, 16, 25])


tensor([ 1,  4,  9, 16, 25])

In [61]:
# you can also do comparisons
print(y > x)
print(torch.any(y < x)) # Any checks if ANYTHING in the array computes to True.
x.equal(y)

tensor([True, True, True, True, True])
tensor(False)


False

What happens if I want to work with a diverse set of tensors?

In [71]:
mat1 = torch.rand([1, 5])
mat2 = torch.rand([10, 5])

print(mat1 - mat2)

tensor([[ 0.8628, -0.1038,  0.4129, -0.0732, -0.6330],
        [ 0.0755, -0.6348,  0.5630,  0.6474, -0.7081],
        [ 0.0591, -0.3593,  0.0787,  0.7404,  0.1373],
        [ 0.4125, -0.2162,  0.7705,  0.7560,  0.0160],
        [ 0.5318, -0.1231,  0.2577,  0.0536, -0.5935],
        [ 0.4864, -0.5760, -0.1544,  0.5075, -0.7491],
        [ 0.8312, -0.5999,  0.7919,  0.2682,  0.0951],
        [ 0.5650, -0.9631, -0.0676,  0.6480, -0.7418],
        [ 0.0297, -0.4487, -0.0793,  0.7420, -0.3449],
        [ 0.1477, -0.1995,  0.2716,  0.6178, -0.4470]])


Why does this work?

because of **Broadcasting!**

Broadcasting basically applies the 1-D tensor over each dimension (row, if you're confused) for the 10x5 tensor.

[Good Source](https://numpy.org/doc/stable/user/basics.broadcasting.html)

Other useful things I found at Torch HQ

In [80]:
# You can shortcut your way to lots of things

# sum!
x = torch.arange(0,5)
y = torch.arange(10,15)
print(torch.sum(x, dtype=torch.int16))

# max, min
values, idx = torch.max(x, dim=0) 
# ^ dim is important here. it specifies where you want the max
print(values, idx)
values, idx = torch.min(y, dim=0) 
print(values, idx)

# argmax, argmin: gives you the idx directly
print(torch.argmax(x, dim=0))


tensor(10, dtype=torch.int16)
tensor(4) tensor(4)
tensor(10) tensor(0)
tensor(4)
